LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_MISC.ALL;

LIBRARY WORK;
USE WORK.TOOLBOX.ALL;

ENTITY EXE_BRANCH_RESOLVE IS 
	
	PORT( 
			RES  : IN  STD_LOGIC_VECTOR(32 DOWNTO 0);
			EQLT : IN  STD_LOGIC;
			INV  : IN  STD_LOGIC;
			T_NT : OUT STD_LOGIC
		);

END EXE_BRANCH_RESOLVE;

ARCHITECTURE RTL OF EXE_BRANCH_RESOLVE IS 
	
	SIGNAL REDUCED_RES : STD_LOGIC;
	SIGNAL MUX_RES     : STD_LOGIC;
	
	BEGIN
	
		REDUCED_RES <= NOR_REDUCE(RES);
		
		MUX: MUX2X1_BIT
			 PORT MAP(
						D0  => RES(32),
						D1  => REDUCED_RES,
						SEL => EQLT,
						O   => MUX_RES
					 );
					  
		T_NT <= MUX_RES XOR INV;
		
END RTL;
	
	